# Generated by Django 4.0.5 on 2022-06-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserhhapp', '0003_alter_cities_percent_alter_skills_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='count',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='count',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
